name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0, v1.2.3)

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21]
        os: [linux, darwin]
        arch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for proper versioning

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Run linter
      run: go vet ./...

    - name: Check formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Code is not formatted. Please run 'go fmt ./...'"
          gofmt -s -l .
          exit 1
        fi

    - name: Build and archive
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: 0
      run: |
        # Set binary name with proper Terraform provider format
        # Terraform expects: terraform-provider-{NAME}_{VERSION}
        BINARY_NAME="terraform-provider-shodan_${{ github.ref_name }}"
        
        # Build with version info and proper platform targeting
        go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" \
          -o "$BINARY_NAME" .
        
        # Create archive name following Terraform Registry naming convention
        # Format: terraform-provider-{NAME}_{VERSION}_{OS}_{ARCH}.zip
        ARCHIVE_NAME="terraform-provider-shodan_${{ github.ref_name }}_${{ matrix.os }}_${{ matrix.arch }}.zip"
        
        # Create ZIP archive with binary at root level (Terraform Registry requirement)
        zip "$ARCHIVE_NAME" "$BINARY_NAME"
        
        # Create artifacts directory structure
        mkdir -p artifacts
        mv "$ARCHIVE_NAME" artifacts/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: terraform-provider-shodan-${{ matrix.os }}-${{ matrix.arch }}
        path: artifacts/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: List downloaded artifacts
      run: |
        echo "Artifacts directory structure:"
        find artifacts -type f -name "*.zip" | sort
        echo "Total .zip files found:"
        find artifacts -type f -name "*.zip" | wc -l

    - name: Generate SHA256SUMS
      run: |
        cd artifacts
        find . -type f -name "*.zip" -exec sha256sum {} + > SHA256SUMS
        echo "Generated SHA256SUMS:"
        cat SHA256SUMS

    - name: Rename SHA256SUMS files with version prefix
      run: |
        cd artifacts
        mv SHA256SUMS "terraform-provider-shodan_${{ github.ref_name }}_SHA256SUMS"
        echo "Renamed SHA256SUMS to terraform-provider-shodan_${{ github.ref_name }}_SHA256SUMS"

    - name: Import GPG key and Sign SHA256SUMS
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      run: |
        echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        gpg --batch --yes --armor --detach-sign --output "artifacts/terraform-provider-shodan_${{ github.ref_name }}_SHA256SUMS.sig" "artifacts/terraform-provider-shodan_${{ github.ref_name }}_SHA256SUMS"
        echo "Generated terraform-provider-shodan_${{ github.ref_name }}_SHA256SUMS.sig"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/**/*.zip
          artifacts/terraform-provider-shodan_${{ github.ref_name }}_SHA256SUMS
          artifacts/terraform-provider-shodan_${{ github.ref_name }}_SHA256SUMS.sig
        generate_release_notes: true
        draft: false
        prerelease: false
        body: |
          ## 🚀 Terraform Provider for Shodan ${{ github.ref_name }}
          
          ### 📦 What's New
          - Automated release with multi-platform binaries
          - Built for Go 1.21
          
          ### 🔧 Supported Platforms
          - **Linux**: AMD64, ARM64
          - **macOS**: AMD64 (Intel), ARM64 (Apple Silicon)
          
          ### 📥 Installation
          Download the appropriate binary for your platform and follow the [Usage instructions](https://github.com/AdconnectDevOps/terraform-provider-shodan?tab=readme-ov-file#-usage).
          
          ### ✅ Verification
          You can verify the integrity of the downloaded files using the `SHA256SUMS` file and its signature `SHA256SUMS.sig`.
          
          ```bash
          # Verify checksums
          sha256sum --check SHA256SUMS
          
          # Verify signature (you'll need to import the signing key first)
          gpg --verify SHA256SUMS.sig SHA256SUMS
          ```
          
          ---
          *This release was automatically generated by GitHub Actions*
