name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0, v1.2.3)

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21]
        os: [linux, darwin]
        arch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for proper versioning

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Run linter
      run: go vet ./...

    - name: Check formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Code is not formatted. Please run 'go fmt ./...'"
          gofmt -s -l .
          exit 1
        fi

    - name: Build and archive
      run: |
        # Set binary name
        BINARY_NAME="terraform-provider-shodan"
        
        # Build with version info
        go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" \
          -o "$BINARY_NAME" .
        
        # Create archive name
        ARCHIVE_NAME="terraform-provider-shodan_${{ github.ref_name }}_${{ matrix.os }}_${{ matrix.arch }}"
        tar -czf "${ARCHIVE_NAME}.tar.gz" "$BINARY_NAME"
        ARCHIVE_NAME="${ARCHIVE_NAME}.tar.gz"
        
        mkdir -p artifacts/${ARCHIVE_NAME%.tar.gz}
        mv "$ARCHIVE_NAME" artifacts/${ARCHIVE_NAME%.tar.gz}/
        mv "$BINARY_NAME" artifacts/${ARCHIVE_NAME%.tar.gz}/ # Keep binary for SHA256SUMS

    - name: Generate SHA256SUMS
      run: |
        cd artifacts
        find . -type f -name "*.tar.gz" -exec sha256sum {} + > SHA256SUMS
        mv SHA256SUMS .. # Move to root for signing and uploading

    - name: Import GPG key and Sign SHA256SUMS
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      run: |
        echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        gpg --batch --yes --armor --detach-sign --output SHA256SUMS.sig SHA256SUMS

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: terraform-provider-shodan-${{ matrix.os }}-${{ matrix.arch }}
        path: |
          ${{ env.ARCHIVE_NAME }}
          ${{ env.BINARY_NAME }}

  create-release:
    needs: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/terraform-provider-shodan-linux-amd64/*.tar.gz
          artifacts/terraform-provider-shodan-linux-arm64/*.tar.gz
          artifacts/terraform-provider-shodan-darwin-amd64/*.tar.gz
          artifacts/terraform-provider-shodan-darwin-arm64/*.tar.gz
          SHA256SUMS
          SHA256SUMS.sig
        generate_release_notes: true
        draft: false
        prerelease: false
        title: "Release ${{ github.ref_name }}"
        body: |
          ## 🚀 Terraform Provider for Shodan ${{ github.ref_name }}
          
          ### 📦 What's New
          - Automated release with multi-platform binaries
          - Built for Go ${{ matrix.go-version }}
          
          ### 🔧 Supported Platforms
          - **Linux**: AMD64, ARM64
          - **macOS**: AMD64 (Intel), ARM64 (Apple Silicon)
          
          ### 📥 Installation
          Download the appropriate binary for your platform and follow the [installation instructions](https://github.com/AdconnectDevOps/terraform-provider-shodan#installation).
          
          ### ✅ Verification
          You can verify the integrity of the downloaded files using the `SHA256SUMS` file and its signature `SHA256SUMS.sig`.
          
          ```bash
          # Verify checksums
          sha256sum --check SHA256SUMS
          
          # Verify signature (you'll need to import the signing key first)
          gpg --verify SHA256SUMS.sig SHA256SUMS
          ```
          
          ### 🔍 Changes
          See the [CHANGELOG](https://github.com/AdconnectDevOps/terraform-provider-shodan/blob/main/CHANGELOG.md) for detailed changes.
          
          ---
          *This release was automatically generated by GitHub Actions*
